/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {},
    colors: {
      primary: {
        default: "var(--ion-color-primary)",
        rgb: "var(--ion-color-primary-rgb)",
        contrast: "var(--ion-color-primary-contrast)",
        constrastRGB: "var(--ion-color-primary-contrast-rgb)",
        shade: "var(--ion-color-primary-shade)",
        tint: "var(--ion-color-primary-tint)",
      },
      secondary: {
        default: "var(--ion-color-secondary)",
        rgb: "var(--ion-color-secondary-rgb)",
        contrast: "var(--ion-color-secondary-contrast)",
        constrastRGB: "var(--ion-color-secondary-contrast-rgb)",
        shade: "var(--ion-color-secondary-shade)",
        tint: "var(--ion-color-secondary-tint)",
      },
      tertiary: {
        default: "var(--ion-color-tertiary)",
        rgb: "var(--ion-color-tertiary-rgb)",
        contrast: "var(--ion-color-tertiary-contrast)",
        constrastRGB: "var(--ion-color-tertiary-contrast-rgb)",
        shade: "var(--ion-color-tertiary-shade)",
        tint: "var(--ion-color-tertiary-tint)",
      },
      success: {
        default: "var(--ion-color-success)",
        rgb: "var(--ion-color-success-rgb)",
        contrast: "var(--ion-color-success-contrast)",
        constrastRGB: "var(--ion-color-success-contrast-rgb)",
        shade: "var(--ion-color-success-shade)",
        tint: "var(--ion-color-success-tint)",
      },
      warning: {
        default: "var(--ion-color-warning)",
        rgb: "var(--ion-color-warning-rgb)",
        contrast: "var(--ion-color-warning-contrast)",
        constrastRGB: "var(--ion-color-warning-contrast-rgb)",
        shade: "var(--ion-color-warning-shade)",
        tint: "var(--ion-color-warning-tint)",
      },
      danger: {
        default: "var(--ion-color-danger)",
        rgb: "var(--ion-color-danger-rgb)",
        contrast: "var(--ion-color-danger-contrast)",
        constrastRGB: "var(--ion-color-danger-contrast-rgb)",
        shade: "var(--ion-color-danger-shade)",
        tint: "var(--ion-color-danger-tint)",
      },
      dark: {
        default: "var(--ion-color-dark)",
        rgb: "var(--ion-color-dark-rgb)",
        contrast: "var(--ion-color-dark-contrast)",
        constrastRGB: "var(--ion-color-dark-contrast-rgb)",
        shade: "var(--ion-color-dark-shade)",
        tint: "var(--ion-color-dark-tint)",
      },
      medium: {
        default: "var(--ion-color-medium)",
        rgb: "var(--ion-color-medium-rgb)",
        contrast: "var(--ion-color-medium-contrast)",
        constrastRGB: "var(--ion-color-medium-contrast-rgb)",
        shade: "var(--ion-color-medium-shade)",
        tint: "var(--ion-color-medium-tint)",
      },
      light: {
        default: "var(--ion-color-light)",
        rgb: "var(--ion-color-light-rgb)",
        contrast: "var(--ion-color-light-contrast)",
        constrastRGB: "var(--ion-color-light-contrast-rgb)",
        shade: "var(--ion-color-light-shade)",
        tint: "var(--ion-color-light-tint)",
      },
    },
  },
  plugins: [],
};
